enchanting-table:
  enabled: true
  tiers:
    common:
      min-level: 1
      max-level: 10
      min-bookshelves: 0
    uncommon:
      min-level: 11
      max-level: 20
      min-bookshelves: 4
    rare:
      min-level: 21
      max-level: 30
      min-bookshelves: 8
    epic:
      min-level: 31
      max-level: 40
      min-bookshelves: 12
    legendary:
      min-level: 41
      max-level: 50
      min-bookshelves: 15
